export const FETCH = 'FETCH';
export const GET = 'GET';

export const USER_LOADING = 'USER/LOADING';
export const USER_LOADED = 'USER/LOADED';

export const AUTH_ERROR = 'AUTH/ERROR';

export const REGISTER_SUCCESS = 'AUTH/REGISTER_SUCCESS';
export const REGISTER_FAIL = 'AUTH/REGISTER_FAIL';

export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS';
export const LOGIN_FAIL = 'AUTH/LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'AUTH/LOGOUT_SUCCESS';

export const GET_ERRORS = 'ERRORS/GET';
export const CLEAR_ERRORS = 'ERRORS/CLEAR';

export const GET_PROPERTIES = 'PROPERTIES/GET';
export const GET_PROPERTIES_ERROR = 'PROPERTIES/GET_ERROR';
export const PROPERTIES_LOADING = 'PROPERTIES/LOADING';

export const CREATE_RENTAL_REQUEST = 'RENTAL_REQUEST/CREATE';
export const CREATE_RENTAL_REQUEST_ERROR = 'RENTAL_REQUEST/CREATE_ERROR';
export const RENTAL_REQUEST_LOADING = 'RENTAL_REQUEST/LOADING';

export const GET_CLAIMS = 'CLAIMS/GET';
export const GET_CLAIM = 'CLAIM/GET';
export const DELETE_CLAIM = 'CLAIM/DELETE';
export const CREATE_CLAIM = 'CLAIM/CREATE';
export const GET_CLAIMS_ERROR = 'CLAIMS/GET_ERROR';
export const CLAIMS_LOADING = 'CLAIMS/LOADING';
