name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run Jest
        working-directory: ./frontend
      - run: yarn install
      - run: yarn test
