name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install deps
        working-directory: ./frontend
        run: yarn install
      - name: run tests
        working-directory: ./frontend
        run: yarn test
