name: Frontend Jest Test Suite
on: [push]
jobs:
  Jest runner:
    env:
      working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
