name: Tests

on: [push]

jobs:
  build:
    env:
      working-directory: ./frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.3
