name: Tests

on: [push]

jobs:
  Jest Runner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Front install deps
        working-directory: ./frontend
        run: yarn install
      - name: Front run tests
        working-directory: ./frontend
        run: yarn test

      - name: Back install deps
        working-directory: ./backend
        run: yarn install
      - name: Back run tests
        working-directory: ./backend
        run: yarn test
